name: deploy auth micro-front-end

on:
  push:
    branches:
      - master
    paths:
      - "packages/auth/**"

defaults:
  run:
    working-directory: packages/auth
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=site --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
