name: deploy auth micro-front-end

on:
  push:
    branches:
      - master
    paths:
      - "packages/auth/**"

  defaults:
    run:
      working-directory: packages/auth
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - run: npm install
        - run: npm run build
        - name: "Deploy to Vercel"
          run: |
            prodRun=""
            if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
              prodRun="--prod"
            fi
            npx vercel --token ${VERCEL_TOKEN} $prodRun
          env:
            VERCEL_PROJECT_ID: ${{ secrets.AUTH_VERCEL_PROJECT_ID }}
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
